ALTER TABLE camps
  ADD COLUMN IF NOT EXISTS logo_url TEXT,
  ADD COLUMN IF NOT EXISTS tagline TEXT,
  ADD COLUMN IF NOT EXISTS whatsapp TEXT,
  ADD COLUMN IF NOT EXISTS features JSONB,
  ADD COLUMN IF NOT EXISTS city_prices JSONB,
  ADD COLUMN IF NOT EXISTS why_us JSONB,
  ADD COLUMN IF NOT EXISTS activities_gallery JSONB;
